name: dynamic_tools
description: Dynamic collection of tools for Flutter development, simplifying usage and some interesting stuff!
version: 2.0.1
repository: https://github.com/rdrgbaioco/dynamic_tools


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1


flutter:
